import React, {Component} from 'react';
class Terms extends Component{
    render(){
        return(
            <div className="container">
                <div className="std"><div className="privacy-content-lo top-head-for-her">
                    <div className="privacy-content">
                        <div className="clearfix">
                            <h2 className="bb">Terms &amp; Conditions</h2>
                        </div>
                        <p>This page, along with the documents referred to on it, outline the terms and conditions under which we supply any of the products listed on our website [www.GlamBox.ME] (our Site) to you via our subscription service (Products). Please read these terms and conditions carefully before subscribing to GlamBox Middle East FZ-LLC or ordering any Products from our site. You should understand that by becoming a member or by ordering any of our Products, you agree to be bound by these terms and conditions.</p>
                        <p>By accessing, browsing or using this Site, you acknowledge that you have read, understood and agreed to be bound by these Terms of Use (these “Terms”). If you do not agree to these Terms, you should not use or access this Site. GlamBox reserves the right to revise these Terms at any time by updating this posting. You are encouraged to review these Terms each time you use the Site because your use of the Site &nbsp;after the posting of changes will constitute your acceptance of the changes.</p>
                        <p>Kindly print a copy of these terms and conditions for future reference.</p>
                    </div>
                </div>
                    <p><br/><br/></p>
                    <div className="privacy-content">
                        <h3>1. Information about us</h3>
                        <p>We operate the website [www.GlamBox.ME] . We are GlamBox Middle East FZ-LLC (GlamBox), a company registered in the UAE under company registration number: 1840/2011CC.<br/>&nbsp;</p>
                        <h3>2. Service availability</h3>
                        <p>At this time, our site is intended for use by people residing in the UAE.&nbsp;<br/>&nbsp;</p>
                        <h3>3. By placing an order through our site, you warrant that</h3>
                        <ul>
                            <li>You are legally capable of entering into binding contracts, and</li>
                            <li>You are at least 18 years old, and</li>
                            <li>You are a resident in the UAE, and</li>
                            <li>You are accessing our site from the UAE</li>
                        </ul>
                        <h3>4. How the contract is formed between you and us</h3>
                        <p>4.1 The Subscription plan to our service consists of an initial charge and then followed by recurring period charges as agreed to by you. By entering into this Agreement, you acknowledge that your subscription at launch has an initial payment. If you accept this recurring payment feature, you will accept responsibility for all recurring charges prior to cancellation. glambox.me may submit periodic charges (e.g. every 3 months) without further authorisation from you, until you provide prior notice that you have terminated this authorisation or wish to change your payment method. Such notice will not affect charges submitted before glambox.me reasonably could act. To terminate your authorisation or change your payment method email us.<br/> 4.2. Subscriptions may be cancelled a notice before the 14th of the month of subscription. You will not be charged for any cancellation. You can re-subscribe at any time following your cancellation.<br/> 4.3 To cancel your subscription at any time, you must email us at info@glambox.me and we will do it for you. If you cancel, you will not be eligibal for a refund.&nbsp;<br/>&nbsp;</p>
                        <h3>5. Consumer rights</h3>
                        <p>5.1 If you are contracting as a consumer, you may cancel your subscription with a notice before the 14th of the month of subscription.<br/> 5.2 To cancel your subscription, you must email us and we will do it for you.<br/> 5.3 Details of your statutory right of cancellation, and an explanation of how to exercise it, are provided in your confirmation email. This provision does not affect your other statutory rights as a consumer.<br/>&nbsp;</p>
                        <h3>6. Fraud Protection</h3>
                        <p>As part of our order processing procedures, we may screen received orders for fraud or other types of unauthorized or illegal activity. We reserve the right to refuse to process an order due to suspected fraud or unauthorized or illegal activity. If we suspect fraudulent, unauthorized or illegal activity, we may reject your order or we may contact you at the phone number or email address you provided to confirm your order. We also reserve the right to cancel any accounts or refuse to ship to certain addresses due to suspected fraud or unauthorized or illegal activity. We take these measures to protect our customers as well as ourselves from fraud or other unauthorized or illegal activity.<br/>&nbsp;</p>
                        <h3>7. Price and payment</h3>
                        <p>7.1 The price of membership can vary from time to time. This does not affect your recurring payments. Delivery is included in your membership fees.<br/> 7.2 Membership fees and delivery charges are liable to change at any time, but changes will not affect orders in respect of which have already been placed, i.e. your recurring payments. <br/> 7.3 We accept Visa and Mastercard credit card payments and Cash on Delivery payments. Your credit card or account will be charged immediately after taking out a membership package.<br/>7.4 Cash on Delivery payments must be paid in full upfront upon the delivery of the first box of your subscription. Failure to pay the full amount will result in return of the first shipment and cancellation of your subscription. You can re-subscribe at any time. <br/> &nbsp;</p>
                        <h3>8. Cancellation of the subscription service</h3>
                        <p>By subscribing to one of our box shipping service contract packages, the Client accepts these Terms and Conditions, and the Client acknowledges having read and understood them, and accepts them without reservation and with full knowledge of cause.</p>
                        <p>3-, 6- or 12-month&nbsp;rebillable For Her Subscriptions can only be cancelled before the 14<sup>th</sup> of the first month of subscription, but we’re able to opt you out of auto-renewal at any time within your subscription period. This must be notified by email to the email address in “Contact us”. You will not be eligible for a refund on any remaining boxes in the subscription as soon as the subscription has started.</p>
                        <p>1-, 2-, or 4-box rebillable For Him subscriptions are not monthly subscriptions. The Client may cancel the order within seven (7) days after the purchase of the subscription or before receiving the first box, whichever instance occurs first. No exchange or refunds beyond these time limits will be accepted. The order(s) shall be deemed irrevocably complete after seven calendar days of the date of purchase or the reception of the first box.</p>
                        <p>All payments are non-refundable.</p>
                        <p>&nbsp;</p>
                        <h3>9. Product information; limitation on quantities</h3>
                        <p>Excluding any content, which may be submitted by Members from time to time, we strive to ensure that the information on the Site is complete and reliable. Certain information may contain pricing errors, typographical errors and other errors or inaccuracies, which we may correct without liability. We also reserve the right to limit quantities purchased by Members and to revise, suspend, or terminate an event or promotion at any time without notice (including after an order has been submitted and/or acknowledged). We do not guarantee that all products described on our Site will be available. We also reserve the right to cancel or block any accounts which are suspected of fraudulent or abusive activity on our website. <br/>&nbsp;</p>
                        <h3>10. User submitted content</h3>
                        <p>GlamBox does not claim ownership of any materials you make available through the Site. With respect to any materials you submit or make available for inclusion on the Site, you grant GlamBox a perpetual, irrevocable, non-terminable, worldwide, royalty-free and non-exclusive license to use, copy, distribute, publicly display, modify, create derivative works, and sublicense such materials or any part of such materials. You hereby represent, warrant and covenant that any materials you provide do not include anything (including, but not limited to, text, images, music or video) to which you do not have the full right to grant GlamBox the license specified above. You further represent, warrant and covenant that any materials you provide will not contain libelous or otherwise unlawful, abusive or obscene material. GlamBox will be entitled to use any content submitted by you without incurring obligations of confidentiality, attribution or compensation to you.<br/>&nbsp;</p>
                        <h3>11. User information</h3>
                        <p>We collect Personally Identifiable Information (“PII”), which you voluntarily provide to us during the registration and process or in response to specific information requests we may present to you. <br/><br/> We may ask for your e-mail address during your use of the Website. To subscribe to GlamBox you may be requested to provide any or all of the following PII: first and last name, postal address, e-mail address, date of birth, telephone number and details of a payment mechanism. We will also ask you to complete a questionnaire so that we may create your beauty profile. It is not compulsory to complete this but will enable us to send products that are more relevant to you. <br/><br/> We may also collect your Internet Protocol (“IP”) address to help diagnose problems with our server, and to administer this Website. An IP address is a number that is assigned to your computer when you use the Internet. Your IP address is also used to help identify you during a particular session and to gather broad demographic data.<br/><br/> In addition to the above, we may collect other information about you using Google Analytics Demographics and Interest Reporting. This information may include your age group, gender, and interest categories as determined by the Google Display Network. We use this information as part of our decision-making and user experience optimization process as informed by Google Analytics, to ensure that we are targeting you with communications and experiences that are deemed relevant to your preferences and needs. Your demographic and interest information will be collected if you have permitted the use of cookies from the Google Display Network on your browser via an opt-in action. You can opt out of Google Analytics for Display Advertising or customize Google Display Networks ads by adjusting the relevant ads settings. <br/><br/> To opt out of having your information being collected by Google Analytics in general, you can download and install the Google Analytics Opt-Out Browser Add-On. <br/><br/> By agreeing to these terms and conditions, you authorise GlamBox to collect such information about you that you have not actively disallowed Google from accessing.<br/>&nbsp;</p>
                        <h3>12. Warranty</h3>
                        <p>We warrant to you that any Product purchased from us through our site will, on delivery, conform to its description, be of satisfactory quality, and be reasonably fit for all the purposes for which products of that kind are commonly supplied.<br/>&nbsp;</p>
                        <h3>13. Limitation of liability</h3>
                        <p>In no event shall GlamBox, its affiliates or any of their respective officers, directors, employees, agents, successors, subsidiaries, suppliers, affiliates, or third parties providing information on this site be liable to any user of the site or any other person or entity for any direct, indirect, special, incidental, punitive, consequential or exemplary damages (including but not limited to, damages for loss of profits, loss of data, or loss of use) arising out of the use or inability to use the site, whether based upon warranty, contract, tort or otherwise, even if GlamBox has been advised or should have known of the possibility of such damages or losses. In no event shall the total liability of GlamBox, its affiliates or any of their respective officers, directors, employees, agents, successors, subsidiaries, suppliers, affiliates, or third parties providing information on this site to you for all damages, losses, and causes of action resulting from your use of this site, whether in contract, tort (including, but not limited to, negligence) or otherwise, exceed the amount you paid to GlamBox in connection with the event giving rise to such liability. You hereby acknowledge that the preceding paragraph shall apply to all content, merchandise and services available through the Site. <br/>&nbsp;</p>
                        <h3>14. Written communications</h3>
                        <p>Applicable laws require that some of the information or communications we send to you should be in writing. When using our site, you accept that communication with us will be mainly electronic. We will contact you by e-mail or provide you with information by posting notices on our website. For contractual purposes, you agree to this electronic means of communication and you acknowledge that all contracts, notices, information and other communications that we provide to you electronically comply with any legal requirement that such communications be in writing. This condition does not affect your statutory rights.<br/>&nbsp;</p>
                        <h3>15. Indemnification</h3>
                        <p>You agree to indemnify, hold harmless, and defend GlamBox, its parent, subsidiaries, divisions, and affiliates, and their respective officers, directors, employees, agents and affiliates from any and all claims, liabilities, damages, costs and expenses of defence, including legal fees, in any way arising from or related to your use of the Site, your violation of these Terms or the Privacy Policy, content posted to the Site by you, or your violation of any law or the rights of a third party.<br/>&nbsp;</p>
                        <h3>16. Notices</h3>
                        <p>All notices given by you to us must be given to GlamBox Middle East at info@glambox.me. We may give notice to you at either the e-mail or postal address you provide to us. Notice will be deemed received and properly served immediately when posted on our website, 24 hours after an e-mail is sent, or three days after the date of posting of any letter.<br/>&nbsp;</p>
                        <h3>17. Transfer of rights and obligations</h3>
                        <p>17.1 The contract between you and us is binding on you and us and on our respective successors and assignees.<br/> 17.2 You may not transfer, assign, charge or otherwise dispose of a Contract, or any of your rights or obligations arising under it, without our prior written consent.<br/> 17.3 We may transfer, assign, charge, sub-contract or otherwise dispose of a Contract, or any of our rights or obligations arising under it, at any time during the term of the Contract.<br/> 17.4 It is at our discretion to renew subscriptions packages.<br/> 17.5 We reserve the right to pass on personal data to specially selected third parties for research purposes.<br/>&nbsp;</p>
                        <h3>18. Events outside our control</h3>
                        <p>18.1 We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations under a Contract that is caused by events outside our reasonable control (Force Majeure Event).<br/> 18.2. A Force Majeure Event includes any act, event, non-happening, omission or accident beyond our reasonable control and includes in particular (without limitation) the following:<br/> 18.2.1 strikes, lockouts or other industrial action;<br/> 18.2.2 civil commotion, riot, invasion, terrorist attack or threat of terrorist attack, war (whether declared or not) or threat or preparation for war;<br/> 17.2.3 fire, explosion, storm, flood, earthquake, subsidence, epidemic or other natural disaster;<br/> 18.2.4 impossibility of the use of railways, shipping, aircraft, motor transport or other means of public or private transport;<br/> 18.2.5 impossibility of the use of public or private telecommunications networks; and<br/> 18.2.6 the acts, decrees, legislation, regulations or restrictions of any government.<br/> 18.3 Our performance under any Contract is deemed to be suspended for the period that the Force Majeure Event continues, and we will have an extension of time for performance for the duration of that period. We will use our reasonable endeavors to bring the Force Majeure Event to a close or to find a solution by which our obligations under the Contract may be performed despite the Force Majeure Event.<br/>&nbsp;</p>
                        <h3>19. Waiver</h3>
                        <p>19.1 If we fail, at any time during the term of a Contract, to insist upon strict performance of any of your obligations under the Contract or any of these terms and conditions, or if we fail to exercise any of the rights or remedies to which we are entitled under the Contract, this will not constitute a waiver of such rights or remedies and will not relieve you from compliance with such obligations.<br/> 19.2 A waiver by us of any default will not constitute a waiver of any subsequent default.<br/> 19.3 No waiver by us of any of these terms and conditions will be effective unless it is expressly stated to be a waiver and is communicated to you in writing in accordance with clause 12 above.<br/>&nbsp;</p>
                        <h3>20. Severability</h3>
                        <p>If any of these terms and Conditions or any provisions of a Contract are determined by any competent authority to be invalid, unlawful or unenforceable to any extent, such term, condition or provision will to that extent be severed from the remaining terms, conditions and provisions which will continue to be valid to the fullest extent permitted by law.<br/>&nbsp;</p>
                        <h3>21. Entire agreement</h3>
                        <p>21.1 These terms and conditions and any document expressly referred to in them constitute the whole agreement between us and supersede all previous discussions, correspondence, negotiations, previous arrangement, understanding or agreement between us relating to the subject matter of any Contract.<br/> 21.2 We each acknowledge that, in entering into a Contract, neither of us relies on any representation or warranty (whether made innocently or negligently) that is not set out in these terms and conditions or the documents referred to in them.<br/> 21.3 Each of us agrees that our only liability in respect of those representations and warranties that are set out in this agreement (whether made innocently or negligently) will be for breach of contract.<br/> 21.4 Nothing in this clause limits or excludes any liability for fraud. <br/>&nbsp;</p>
                        <h3>22. Our right to vary these terms and conditions</h3>
                        <p>22.1 We have the right to revise and amend these terms and conditions from time to time to reflect changes in market conditions affecting our business, changes in technology, changes in payment methods, changes in relevant laws and regulatory requirements and changes in our system's capabilities.<br/> 22.2 You will be subject to the policies and terms and conditions in force at the time that you order products from us, unless any change to those policies or these terms and conditions is required to be made by law or governmental authority (in which case it will apply to orders previously placed by you), or if we notify you of the change to those policies or these terms and conditions before we send you the Dispatch Confirmation (in which case we have the right to assume that you have accepted the change to the terms and conditions, unless you notify us to the contrary within seven working days of receipt by you of the Products). <br/>&nbsp;</p>
                        <h3>23. Law and jurisdiction</h3>
                        <p>Contracts for the purchase of Products through our site and any dispute or claim arising out of or in connection with them or their subject matter or formation (including non-contractual disputes or claims) will be governed by the UAE law. Any dispute or claim arising out of or in connection with such Contracts or their formation (including non-contractual disputes or claims) will be subject to the non-exclusive jurisdiction of the courts of the UAE.<br/>&nbsp;</p>
                    </div></div>
            </div>
        )
    }
}
export default Terms;