import React, {Component} from 'react';
import { Translate } from 'react-localize-redux';
class Terms extends Component{
    render(){
        return(
            <div className="container">
                <div className="std"><div className="privacy-content-lo top-head-for-her">
                    <div className="privacy-content">
                        <div className="clearfix">
                            <h2 className="bb"><Translate id="nave.termsandconditions"/></h2>
                        </div>
                        <p><Translate id="nave.para1">This page, along with the documents referred to on it, outline the terms and conditions under which we supply any of the products listed on our website [www.beautybox.ME] (our Site) to you via our subscription service (Products). Please read these terms and conditions carefully before subscribing to BeautyBox Middle East FZ-LLC or ordering any Products from our site. You should understand that by becoming a member or by ordering any of our Products, you agree to be bound by these terms and conditions.</Translate></p>
                        <p><Translate id="nave.para2">By accessing, browsing or using this Site, you acknowledge that you have read, understood and agreed to be bound by these Terms of Use (these “Terms”). If you do not agree to these Terms, you should not use or access this Site. BeautyBox reserves the right to revise these Terms at any time by updating this posting. You are encouraged to review these Terms each time you use the Site because your use of the Site after the posting of changes will constitute your acceptance of the changes.</Translate></p>
                        <p><Translate id="nave.para3">Kindly print a copy of these terms and conditions for future reference.</Translate></p>
                    </div>
                </div>
                    <p><br/><br/></p>
                    <div className="privacy-content">
                        <h3><Translate id="nave.heading1">1. Information about us</Translate></h3>
                        <p><Translate id="nave.para4">We operate the website [www.BeautyBox.ME] . We are BeautyBox Middle East FZ-LLC (BeautyBox), a company registered in the UAE under company registration number: 1840/2011CC.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading2">2. Service availability</Translate></h3>
                        <p><Translate id="nave.para5">At this time, our site is intended for use by people residing in the UAE.</Translate>&nbsp;<br/>&nbsp;</p>
                        <h3><Translate id="nave.heading3">3. By placing an order through our site, you warrant that</Translate></h3>
                        <ul>
                            <li><Translate id="nave.para6-1">You are legally capable of entering into binding contracts, and</Translate></li>
                            <li><Translate id="nave.para6-2">You are at least 18 years old, and</Translate></li>
                            <li><Translate id="nave.para6-3">You are a resident in the UAE, and</Translate></li>
                            <li><Translate id="nave.para6-4">You are accessing our site from the UAE</Translate></li>
                        </ul>
                        <h3><Translate id="nave.heading4">4. How the contract is formed between you and us</Translate></h3>
                        <p><Translate id="nave.para7-1">4.1 The Subscription plan to our service consists of an initial charge and then followed by recurring period charges as agreed to by you. By entering into this Agreement, you acknowledge that your subscription at launch has an initial payment. If you accept this recurring payment feature, you will accept responsibility for all recurring charges prior to cancellation. BeautyBox.me may submit periodic charges (e.g. every 3 months) without further authorisation from you, until you provide prior notice that you have terminated this authorisation or wish to change your payment method. Such notice will not affect charges submitted before BeautyBox.me reasonably could act. To terminate your authorisation or change your payment method email us.</Translate><br/> 4.2.<Translate id="nave.para7-2"> Subscriptions may be cancelled a notice before the 14th of the month of subscription. You will not be charged for any cancellation. You can re-subscribe at any time following your cancellation.</Translate><br/> 4.3<Translate id="nave.para7-3"> To cancel your subscription at any time, you must email us at info@BeautyBox.me and we will do it for you. If you cancel, you will not be eligibal for a refund.</Translate>&nbsp;<br/>&nbsp;</p>
                        <h3><Translate id="nave.heading5">5. Consumer rights</Translate></h3>
                        <p><Translate id="nave.para8-1">5.1 If you are contracting as a consumer, you may cancel your subscription with a notice before the 14th of the month of subscription.</Translate><br/><Translate id="nave.para8-2"> 5.2 To cancel your subscription, you must email us and we will do it for you.</Translate><br/><Translate id="nave.para8-3"> 5.3 Details of your statutory right of cancellation, and an explanation of how to exercise it, are provided in your confirmation email. This provision does not affect your other statutory rights as a consumer.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading6">6. Fraud Protection</Translate></h3>
                        <p><Translate id="nave.para9">As part of our order processing procedures, we may screen received orders for fraud or other types of unauthorized or illegal activity. We reserve the right to refuse to process an order due to suspected fraud or unauthorized or illegal activity. If we suspect fraudulent, unauthorized or illegal activity, we may reject your order or we may contact you at the phone number or email address you provided to confirm your order. We also reserve the right to cancel any accounts or refuse to ship to certain addresses due to suspected fraud or unauthorized or illegal activity. We take these measures to protect our customers as well as ourselves from fraud or other unauthorized or illegal activity.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading7">7. Price and payment</Translate></h3>
                        <p><Translate id="nave.para10-1">7.1 The price of membership can vary from time to time. This does not affect your recurring payments. Delivery is included in your membership fees.</Translate><br/> <Translate id="nave.para10-2">7.2 Membership fees and delivery charges are liable to change at any time, but changes will not affect orders in respect of which have already been placed, i.e. your recurring payments.</Translate> <br/> <Translate id="nave.para10-3">7.3 We accept Visa and Mastercard credit card payments and Cash on Delivery payments. Your credit card or account will be charged immediately after taking out a membership package.</Translate><br/><Translate id="nave.para10-4">7.4 Cash on Delivery payments must be paid in full upfront upon the delivery of the first box of your subscription. Failure to pay the full amount will result in return of the first shipment and cancellation of your subscription. You can re-subscribe at any time.</Translate> <br/> &nbsp;</p>
                        <h3><Translate id="nave.heading8">8. Cancellation of the subscription service</Translate></h3>
                        <p><Translate id="nave.para11-1">By subscribing to one of our box shipping service contract packages, the Client accepts these Terms and Conditions, and the Client acknowledges having read and understood them, and accepts them without reservation and with full knowledge of cause.</Translate></p>
                        <p><Translate id="nave.para11-2"/></p>
                        <p><Translate id="nave.para11-3">1-, 2-, or 4-box rebillable For Him subscriptions are not monthly subscriptions. The Client may cancel the order within seven (7) days after the purchase of the subscription or before receiving the first box, whichever instance occurs first. No exchange or refunds beyond these time limits will be accepted. The order(s) shall be deemed irrevocably complete after seven calendar days of the date of purchase or the reception of the first box.</Translate></p>
                        <p><Translate id="nave.para11-4">All payments are non-refundable.</Translate></p>
                        <p>&nbsp;</p>
                        <h3><Translate id="nave.heading9">9. Product information; limitation on quantities</Translate></h3>
                        <p><Translate id="nave.para12">Excluding any content, which may be submitted by Members from time to time, we strive to ensure that the information on the Site is complete and reliable. Certain information may contain pricing errors, typographical errors and other errors or inaccuracies, which we may correct without liability. We also reserve the right to limit quantities purchased by Members and to revise, suspend, or terminate an event or promotion at any time without notice (including after an order has been submitted and/or acknowledged). We do not guarantee that all products described on our Site will be available. We also reserve the right to cancel or block any accounts which are suspected of fraudulent or abusive activity on our website.</Translate>
                         <br/>&nbsp;</p>
                        <h3><Translate id="nave.heading10">10. User submitted content</Translate></h3>
                        <p><Translate id="nave.para13">BeautyBox does not claim ownership of any materials you make available through the Site. With respect to any materials you submit or make available for inclusion on the Site, you grant BeautyBox a perpetual, irrevocable, non-terminable, worldwide, royalty-free and non-exclusive license to use, copy, distribute, publicly display, modify, create derivative works, and sublicense such materials or any part of such materials. You hereby represent, warrant and covenant that any materials you provide do not include anything (including, but not limited to, text, images, music or video) to which you do not have the full right to grant BeautyBox the license specified above. You further represent, warrant and covenant that any materials you provide will not contain libelous or otherwise unlawful, abusive or obscene material. BeautyBox will be entitled to use any content submitted by you without incurring obligations of confidentiality, attribution or compensation to you.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading11">11. User information</Translate></h3>
                        <p><Translate id="nave.para14-1">We collect Personally Identifiable Information (“PII”), which you voluntarily provide to us during the registration and process or in response to specific information requests we may present to you.</Translate> <br/><br/> <Translate id="nave.para14-2">We may ask for your e-mail address during your use of the Website. To subscribe to BeautyBox you may be requested to provide any or all of the following PII: first and last name, postal address, e-mail address, date of birth, telephone number and details of a payment mechanism. We will also ask you to complete a questionnaire so that we may create your beauty profile. It is not compulsory to complete this but will enable us to send products that are more relevant to you.</Translate> <br/><br/> <Translate id="nave.para14-3">We may also collect your Internet Protocol (“IP”) address to help diagnose problems with our server, and to administer this Website. An IP address is a number that is assigned to your computer when you use the Internet. Your IP address is also used to help identify you during a particular session and to gather broad demographic data.</Translate><br/><br/> <Translate id="nave.para14-4">In addition to the above, we may collect other information about you using Google Analytics Demographics and Interest Reporting. This information may include your age group, gender, and interest categories as determined by the Google Display Network. We use this information as part of our decision-making and user experience optimization process as informed by Google Analytics, to ensure that we are targeting you with communications and experiences that are deemed relevant to your preferences and needs. Your demographic and interest information will be collected if you have permitted the use of cookies from the Google Display Network on your browser via an opt-in action. You can opt out of Google Analytics for Display Advertising or customize Google Display Networks ads by adjusting the relevant ads settings.</Translate> <br/><br/> <Translate id="nave.para14-5">To opt out of having your information being collected by Google Analytics in general, you can download and install the Google Analytics Opt-Out Browser Add-On.</Translate> <br/><br/> <Translate id="nave.para14-6">By agreeing to these terms and conditions, you authorise BeautyBox to collect such information about you that you have not actively disallowed Google from accessing.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading12">12. Warranty</Translate></h3>
                        <p><Translate id="nave.para15">We warrant to you that any Product purchased from us through our site will, on delivery, conform to its description, be of satisfactory quality, and be reasonably fit for all the purposes for which products of that kind are commonly supplied.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading13">13. Limitation of liability</Translate></h3>
                        <p><Translate id="nave.para16">In no event shall BeautyBox, its affiliates or any of their respective officers, directors, employees, agents, successors, subsidiaries, suppliers, affiliates, or third parties providing information on this site be liable to any user of the site or any other person or entity for any direct, indirect, special, incidental, punitive, consequential or exemplary damages (including but not limited to, damages for loss of profits, loss of data, or loss of use) arising out of the use or inability to use the site, whether based upon warranty, contract, tort or otherwise, even if BeautyBox has been advised or should have known of the possibility of such damages or losses. In no event shall the total liability of BeautyBox, its affiliates or any of their respective officers, directors, employees, agents, successors, subsidiaries, suppliers, affiliates, or third parties providing information on this site to you for all damages, losses, and causes of action resulting from your use of this site, whether in contract, tort (including, but not limited to, negligence) or otherwise, exceed the amount you paid to BeautyBox in connection with the event giving rise to such liability. You hereby acknowledge that the preceding paragraph shall apply to all content, merchandise and services available through the Site.</Translate> <br/>&nbsp;</p>
                        <h3><Translate id="nave.heading14">14. Written communications</Translate></h3>
                        <p><Translate id="nave.para17">Applicable laws require that some of the information or communications we send to you should be in writing. When using our site, you accept that communication with us will be mainly electronic. We will contact you by e-mail or provide you with information by posting notices on our website. For contractual purposes, you agree to this electronic means of communication and you acknowledge that all contracts, notices, information and other communications that we provide to you electronically comply with any legal requirement that such communications be in writing. This condition does not affect your statutory rights.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading15">15. Indemnification</Translate></h3>
                        <p><Translate id="nave.para18">You agree to indemnify, hold harmless, and defend BeautyBox, its parent, subsidiaries, divisions, and affiliates, and their respective officers, directors, employees, agents and affiliates from any and all claims, liabilities, damages, costs and expenses of defence, including legal fees, in any way arising from or related to your use of the Site, your violation of these Terms or the Privacy Policy, content posted to the Site by you, or your violation of any law or the rights of a third party.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading16">16. Notices</Translate></h3>
                        <p><Translate id="nave.para19">All notices given by you to us must be given to BeautyBox Middle East at info@BeautyBox.me. We may give notice to you at either the e-mail or postal address you provide to us. Notice will be deemed received and properly served immediately when posted on our website, 24 hours after an e-mail is sent, or three days after the date of posting of any letter.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading17">17. Transfer of rights and obligations</Translate></h3>
                        <p><Translate id="nave.para20-1">17.1 The contract between you and us is binding on you and us and on our respective successors and assignees.</Translate><br/> <Translate id="nave.para20-2">17.2 You may not transfer, assign, charge or otherwise dispose of a Contract, or any of your rights or obligations arising under it, without our prior written consent.</Translate><br/> <Translate id="nave.para20-3">17.3 We may transfer, assign, charge, sub-contract or otherwise dispose of a Contract, or any of our rights or obligations arising under it, at any time during the term of the Contract.</Translate><br/> <Translate id="nave.para20-4">17.4 It is at our discretion to renew subscriptions packages.</Translate><br/> <Translate id="nave.para20-5">17.5 We reserve the right to pass on personal data to specially selected third parties for research purposes.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading18">18. Events outside our control</Translate></h3>
                        <p><Translate id="nave.para21-1">18.1 We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations under a Contract that is caused by events outside our reasonable control (Force Majeure Event).</Translate><br/> <Translate id="nave.para21-2">18.2. A Force Majeure Event includes any act, event, non-happening, omission or accident beyond our reasonable control and includes in particular (without limitation) the following:</Translate><br/> <Translate id="nave.para21-3">18.2.1 strikes, lockouts or other industrial action;</Translate><br/> <Translate id="nave.para21-4">18.2.2 civil commotion, riot, invasion, terrorist attack or threat of terrorist attack, war (whether declared or not) or threat or preparation for war;</Translate><br/> <Translate id="nave.para21-5">17.2.3 fire, explosion, storm, flood, earthquake, subsidence, epidemic or other natural disaster;</Translate><br/> <Translate id="nave.para21-6">18.2.4 impossibility of the use of railways, shipping, aircraft, motor transport or other means of public or private transport;</Translate><br/> <Translate id="nave.para21-7">18.2.5 impossibility of the use of public or private telecommunications networks; and</Translate><br/> <Translate id="nave.para21-8">18.2.6 the acts, decrees, legislation, regulations or restrictions of any government.</Translate><br/> <Translate id="nave.para21-9">18.3 Our performance under any Contract is deemed to be suspended for the period that the Force Majeure Event continues, and we will have an extension of time for performance for the duration of that period. We will use our reasonable endeavors to bring the Force Majeure Event to a close or to find a solution by which our obligations under the Contract may be performed despite the Force Majeure Event.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading19">19. Waiver</Translate></h3>
                        <p><Translate id="nave.para22-1">19.1 If we fail, at any time during the term of a Contract, to insist upon strict performance of any of your obligations under the Contract or any of these terms and conditions, or if we fail to exercise any of the rights or remedies to which we are entitled under the Contract, this will not constitute a waiver of such rights or remedies and will not relieve you from compliance with such obligations.</Translate><br/> <Translate id="nave.para22-2">19.2 A waiver by us of any default will not constitute a waiver of any subsequent default.</Translate><br/> <Translate id="nave.para22-3">19.3 No waiver by us of any of these terms and conditions will be effective unless it is expressly stated to be a waiver and is communicated to you in writing in accordance with clause 12 above.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading20">20. Severability</Translate></h3>
                        <p><Translate id="nave.para23">If any of these terms and Conditions or any provisions of a Contract are determined by any competent authority to be invalid, unlawful or unenforceable to any extent, such term, condition or provision will to that extent be severed from the remaining terms, conditions and provisions which will continue to be valid to the fullest extent permitted by law.</Translate><br/>&nbsp;</p>
                        <h3><Translate id="nave.heading21">21. Entire agreement</Translate></h3>
                        <p><Translate id="nave.para24-1">21.1 These terms and conditions and any document expressly referred to in them constitute the whole agreement between us and supersede all previous discussions, correspondence, negotiations, previous arrangement, understanding or agreement between us relating to the subject matter of any Contract.</Translate><br/> <Translate id="nave.para24-2">21.2 We each acknowledge that, in entering into a Contract, neither of us relies on any representation or warranty (whether made innocently or negligently) that is not set out in these terms and conditions or the documents referred to in them.</Translate><br/> <Translate id="nave.para24-3">21.3 Each of us agrees that our only liability in respect of those representations and warranties that are set out in this agreement (whether made innocently or negligently) will be for breach of contract.</Translate><br/> <Translate id="nave.para24-4">21.4 Nothing in this clause limits or excludes any liability for fraud.</Translate> <br/>&nbsp;</p>
                        <h3><Translate id="nave.heading22">22. Our right to vary these terms and conditions</Translate></h3>
                        <p><Translate id="nave.para25-1">22.1 We have the right to revise and amend these terms and conditions from time to time to reflect changes in market conditions affecting our business, changes in technology, changes in payment methods, changes in relevant laws and regulatory requirements and changes in our system's capabilities.</Translate><br/> <Translate id="nave.para25-2">22.2 You will be subject to the policies and terms and conditions in force at the time that you order products from us, unless any change to those policies or these terms and conditions is required to be made by law or governmental authority (in which case it will apply to orders previously placed by you), or if we notify you of the change to those policies or these terms and conditions before we send you the Dispatch Confirmation (in which case we have the right to assume that you have accepted the change to the terms and conditions, unless you notify us to the contrary within seven working days of receipt by you of the Products).</Translate> <br/>&nbsp;</p>
                        <h3><Translate id="nave.heading23">23. Law and jurisdiction</Translate></h3>
                        <p><Translate id="nave.para26">Contracts for the purchase of Products through our site and any dispute or claim arising out of or in connection with them or their subject matter or formation (including non-contractual disputes or claims) will be governed by the UAE law. Any dispute or claim arising out of or in connection with such Contracts or their formation (including non-contractual disputes or claims) will be subject to the non-exclusive jurisdiction of the courts of the UAE.</Translate><br/>&nbsp;</p>
                    </div></div>
            </div>
        )
    }
}
export default Terms;